### PR TITLE
feat(media_data): add info about most currently used sources in kite

### PR DESCRIPTION
**Pull request by GiorgioBrux**
This PR adds metadata for most news sources currently active in Kite's feeds. 

Unused media entries have been removed to optimize the client-side payload. 
Previous entries remain accessible in the commit history if needed for future use.

- [x] World
- [x] USA
- [x] Business
- [x] Technology
- [x] Science
- [x] Sports
- [x] Gaming
- [x] Bay Area
- [x] Linux & OSS
- [x] Cryptocurrency
- [x] Germany
- [x] Italy

These categories are planned for a later time:
- Europe
- UK
- Brazil
- Australia
- Estonia
- Mexico
- Canada
- Thai
- Vermont

### CODE REVIEW

**Comment by vprelovac** [comment]
Great job! Can you make sure some staples like aljazeera, france24, rt.com are covered in the db first

**Comment by vprelovac** [comment]
Good to merge?

**Comment by GiorgioBrux** [comment]
> Good to merge?

Cleaning up some stuff and we should be good!

**Comment by GiorgioBrux** [comment]
Should be ready to merge now :)

**Comment by vprelovac** [comment]
Amazing work!

**Pull request merged**
